name: shopping
environment:
ingress:
  hosts:
    - host: shopping.ecommerce-store-builder.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: shopping-tls
      hosts:
        - shopping.ecommerce-store-builder.com