# DigitalOcean Cert Manager
# https://marketplace.digitalocean.com/apps/cert-manager
# https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/03-setup-ingress-controller/nginx.md
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer
spec:
  acme:
    email: peterkneale@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-private-key
    solvers:
      - http01:
          ingress:
            class: nginx