name: management
environment:
ingress:
  hosts:
    - host: management.ecommerce-store-builder.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: management-tls
      hosts:
        - management.ecommerce-store-builder.com