name: "Deploy"
description: "Deploys a helm chart to AKS"

inputs:
  digitalocean_access_token:
    description: "Digital ocean access token"
    required: true
  component_name:
    description: "Name of component to deploy e.g. carts"
    required: true
  component_type:
    description: "Type of component to deploy e.g. service"
    required: true
  environment:
    description: "Environment to deploy to e.g. developement"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install DigitalOcean CLI
    uses: digitalocean/action-doctl@v2
    with:
      token: ${{ inputs.digitalocean_access_token }}

  - name: Save DigitalOcean kubeconfig
    shell: bash
    run: doctl kubernetes cluster kubeconfig save cluster
  
  - name: Deploy Chart
    shell: bash
    run: |
      helm upgrade \
        --install ${{ inputs.component_type }}-${{ inputs.component_name }} \
        --namespace saas-app-${{ inputs.k8s_namespace }} \
        ./deploy/chart \
          -f ./deploy/environments/common.yaml \
          -f ./deploy/environments/${{ inputs.environment }}.yaml \
          -f ./deploy/${{ inputs.component_type }}s/common.yaml \
          -f ./deploy/${{ inputs.component_type }}s/${{ inputs.component_name }}.yaml