name: admin
ingress:
  hosts:
    - host: admin.ecommerce-store-builder.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: admin-tls
      hosts:
        - admin.ecommerce-store-builder.dev