name: backend_registration

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

    paths:
      - src/building_blocks/**
      - src/backends/registration/**
      - .github/workflows/backend_registration.yml

  pull_request:
    branches:
      - main

    paths:
      - src/building_blocks/**
      - src/backends/registration/**
      - .github/workflows/backend_registration.yml

env:
  COMPONENT: backend_registration
  IMAGE: backend_registration

jobs:

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/build
        with:
          component: ${{ env.COMPONENT }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
      - uses: ./.github/workflows/composite/unit_test
        with:
          component: ${{ env.COMPONENT }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}

  push:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/push
        with:
          component: ${{ env.COMPONENT }}
          image_name: ${{ env.IMAGE }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}