name: frontend_marketing_deploy

on:
  workflow_run:
    workflows: ["frontend_marketing_build"]
    branches: [main]
    types: [completed]

env:
  COMPONENT_NAME: marketing
  COMPONENT_TYPE: frontend

jobs:

  deploy:  
    environment: development    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/deploy
        with:
          environment: development
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          digitalocean_access_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}