name: frontend_admin_deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - deploy
  push:
    branches:
      - main
    paths:
      - deploy/config/environments/common.yaml
      - deploy/config/environments/development.yaml
      - deploy/config/frontends/common.yaml
      - deploy/config/frontends/admin/common.yaml
      - deploy/config/frontends/admin/development.yaml

  workflow_run:
    workflows: ["frontend_admin_build"]
    branches: [main]
    types: [completed]

env:
  COMPONENT_NAME: admin
  COMPONENT_TYPE: frontend

jobs:

  deploy:  
    environment: development    
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/deploy
        with:
          environment: development
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          digitalocean_access_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}