name: service_carts_build

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

    paths:
      - src/building_blocks/**
      - src/services/carts/**
      - .github/workflows/service_carts.yaml

  pull_request:
    branches:
      - main

    paths:
      - src/building_blocks/**
      - src/services/carts/**
      - .github/workflows/service_carts.yaml

env:
  COMPONENT_NAME: carts
  COMPONENT_TYPE: service

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/build
        with:
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
      - uses: ./.github/workflows/composite/unit_test
        with:
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}

  push:
    needs: [build]
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/push
        with:
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}