name: service_media_deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - deploy
  push:
    branches:
      - main
    paths:
      - deploy/environments/common.yaml
      - deploy/environments/development.yaml
      - deploy/services/common.yaml
      - deploy/services/media.yaml

env:
  COMPONENT_NAME: media
  COMPONENT_TYPE: service

jobs:

  deploy:
    runs-on: ubuntu-latest      
    environment: development  
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/deploy
        with:
          digitalocean_access_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          environment: development