name: service_search_config

on:
  push:
    branches:
      - main
    paths:
      - deploy/app/config/environments/common.yaml
      - deploy/app/config/environments/development.yaml
      - deploy/app/config/services/common.yaml
      - deploy/app/config/services/search/common.yaml
      - deploy/app/config/services/search/development.yaml

env:
  COMPONENT_NAME: search
  COMPONENT_TYPE: service

jobs:

  deploy:  
    environment: development
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/deploy
        with:
          environment: development
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          digitalocean_access_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}