name: service_catalog

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

    paths:
      - src/building_blocks/**
      - src/services/catalog/**
      - .github/workflows/service_catalog.yml

  pull_request:
    branches:
      - main

    paths:
      - src/building_blocks/**
      - src/services/catalog/**
      - .github/workflows/service_catalog.yml

env:
  COMPONENT: service_catalog
  IMAGE: service_catalog

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/build
        with:
          component: ${{ env.COMPONENT }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
      - uses: ./.github/workflows/composite/unit_test
        with:
          component: ${{ env.COMPONENT }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}

  push:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/push
        with:
          component: ${{ env.COMPONENT }}
          image_name: ${{ env.IMAGE }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}